# Generated by Django 4.2.3 on 2023-07-07 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted', models.BooleanField()),
                ('junk', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('team', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='video',
            name='videofile',
        ),
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_url', models.TextField()),
                ('pred_cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pred_tracks', to='myapp.cluster')),
                ('true_cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='true_tracks', to='myapp.cluster')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.video')),
            ],
        ),
        migrations.AddField(
            model_name='cluster',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.person'),
        ),
        migrations.AddField(
            model_name='video',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.game'),
        ),
    ]
