# Generated by Django 4.2.3 on 2023-08-08 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_cluster_game_person_remove_video_videofile_video_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='url',
        ),
    ]
