# Generated by Django 4.2.3 on 2023-08-09 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_cluster_id_remove_game_id_remove_person_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.person'),
        ),
    ]
