# Generated by Django 4.2.3 on 2023-08-09 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_video_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(max_length=500, primary_key=True, serialize=False, unique=True),
        ),
    ]
