# Generated by Django 4.2.3 on 2023-08-09 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_game_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='description',
        ),
    ]
