# Generated by Django 4.2.3 on 2023-08-09 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_game_id_alter_game_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
