# Generated by Django 4.2.3 on 2023-08-09 21:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_game_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 21, 14, 2, 812198, tzinfo=datetime.timezone.utc)),
            preserve_default=True
        ),
    ]
