# Generated by Django 4.2.3 on 2023-08-10 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_game_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='game',
            field=models.ForeignKey(blank=True, db_column='game_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.game'),
        ),
    ]
