# Generated by Django 4.2.3 on 2023-08-10 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_video_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.person'),
        ),
    ]
