# Generated by Django 4.2.3 on 2023-08-10 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_person_id_alter_person_name'),
    ]

    operations = [

        migrations.AlterField(
            model_name='video',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AddField(
            model_name='video',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
