# Generated by Django 4.2.3 on 2023-08-10 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_video_id_alter_video_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.person'),
        ),
    ]
