# Generated by Django 4.2.3 on 2023-08-10 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_alter_cluster_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='frame_url',
            new_name='frame_name',
        ),
    ]
