# Generated by Django 4.2.3 on 2023-08-10 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_rename_frame_url_track_frame_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='true_cluster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='true_tracks', to='myapp.cluster'),
        ),
    ]
