# Generated by Django 4.2.3 on 2023-08-21 16:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_alter_track_true_cluster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='frame_name',
        ),
        migrations.AddField(
            model_name='track',
            name='bboxes',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), null=True, size=None),
        ),
        migrations.AddField(
            model_name='track',
            name='lifetime',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None),
        ),
    ]
