# Generated by Django 4.2.3 on 2023-08-21 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_remove_track_frame_name_track_bboxes_track_lifetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cluster', to='myapp.video'),
        ),
        migrations.AlterField(
            model_name='track',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='myapp.video'),
        ),
        migrations.AlterField(
            model_name='video',
            name='game',
            field=models.ForeignKey(blank=True, db_column='game_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='myapp.game'),
        ),
    ]
