# Generated by Django 4.2.3 on 2023-08-23 22:00

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_cluster_video_alter_track_video_alter_video_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='dim',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None),
        ),
        migrations.AddField(
            model_name='video',
            name='fps',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to='myapp.video'),
        ),
    ]
