# Generated by Django 4.2.3 on 2023-08-23 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_video_dim_video_fps_alter_cluster_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='dim',
        ),
        migrations.AddField(
            model_name='video',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='width',
            field=models.IntegerField(null=True),
        ),
    ]
